#!/bin/sh
# Docker entrypoint script to generate runtime config.js

set -e

# Default API_BASE_URL if not provided
API_BASE_URL="${API_BASE_URL:-http://localhost:8000}"

echo "🐳 Generating runtime config with API_BASE_URL=${API_BASE_URL}"

# Generate config.js with runtime environment variables
cat > /usr/share/nginx/html/config.js <<EOF
// Runtime configuration - generated by Docker entrypoint
window.__ENV__ = {
  API_BASE_URL: "${API_BASE_URL}",
};
EOF

echo "✅ Runtime config.js generated successfully"

# Execute the main container command (nginx)
exec "$@"
