// Wine-producing countries with ISO 3166-1 alpha-2 codes
export const WINE_COUNTRIES = [
  { code: "FR", label: "Frankrijk" },
  { code: "IT", label: "Italië" },
  { code: "ES", label: "Spanje" },
  { code: "PT", label: "Portugal" },
  { code: "DE", label: "Duitsland" },
  { code: "AT", label: "Oostenrijk" },
  { code: "GR", label: "Griekenland" },
  { code: "HU", label: "Hongarije" },
  { code: "RO", label: "Roemenië" },
  { code: "BG", label: "Bulgarije" },
  { code: "CH", label: "Zwitserland" },
  { code: "GB", label: "Verenigd Koninkrijk" },
  { code: "LU", label: "Luxemburg" },
  { code: "SI", label: "Slovenië" },
  { code: "HR", label: "Kroatië" },
  { code: "CZ", label: "Tsjechië" },
  { code: "SK", label: "Slowakije" },
  { code: "MD", label: "Moldavië" },
  { code: "GE", label: "Georgië" },
  { code: "US", label: "Verenigde Staten" },
  { code: "CA", label: "Canada" },
  { code: "MX", label: "Mexico" },
  { code: "AR", label: "Argentinië" },
  { code: "CL", label: "Chili" },
  { code: "BR", label: "Brazilië" },
  { code: "UY", label: "Uruguay" },
  { code: "ZA", label: "Zuid-Afrika" },
  { code: "AU", label: "Australië" },
  { code: "NZ", label: "Nieuw-Zeeland" },
  { code: "CN", label: "China" },
  { code: "JP", label: "Japan" },
  { code: "IN", label: "India" },
  { code: "IL", label: "Israël" },
  { code: "LB", label: "Libanon" },
  { code: "TR", label: "Turkije" },
  { code: "MA", label: "Marokko" },
  { code: "TN", label: "Tunesië" },
];

// Sort countries alphabetically by label
WINE_COUNTRIES.sort((a, b) => a.label.localeCompare(b.label, "nl"));
